починил Network Info
5gst/5gst pull request #22
Opened 2023-07-26 19:47 UTC by AndyForWork

#18

2023-07-26 20:54 UTC, AdvancerMan requested changes
Да, похоже на правду, давай это еще порефакторим

2023-07-26 20:54 UTC, AdvancerMan commented on .github/workflows/main_workflow.yml
> +    uses: ./.github/workflows/making_artifacts.yml
это не должно было попасть в этот пр

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/NetworkInfoTab.kt
> +    private  lateinit var permitBtn: Button
Давай именовать поля полностью: `permitButton`

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/NetworkInfoTab.kt
> +        permitBtn.setOnClickListener {permitRequest()}
форматирование поехало, либо так
```
permitBtn.setOnClickListener { permitRequest() } // добавились пробелы внутри {}
```
либо так
```
permitBtn.setOnClickListener {
    permitRequest()
}
```

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/NetworkInfoTab.kt
> +    private fun permitRequest(){
а сделай ctrl + alt + L в файле

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/NetworkInfoTab.kt
> +    private fun permitRequest(){
методы именуются не существительными а глаголами, конкретно тут я ожидаю `requestPermissions()`

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/NetworkInfoTab.kt
> +        else {
давай тут сделаем guard if, чтобы не складывать кучу кода под else
в ифе добавим return, а else уберем

2023-07-26 20:54 UTC, AdvancerMan commented on application/app/src/main/res/layout/network_info_tab.xml
> +        android:backgroundTint="#0f62fe"
цвет стоит использовать как @ color/id

2023-07-30 10:01 UTC, AndyForWork commented on application/app/src/main/res/layout/network_info_tab.xml
> +        android:backgroundTint="#0f62fe"
так ведь в других лэйаутах так сделано (например в dev_tools_tab.xml)

2023-07-30 16:04 UTC, AndyForWork commented
не знаю критично это или нет, но заметил что если 2 раза отказаться от какого-то запроса, то при следующем нажатии кнопки окно не появится.

2023-07-31 07:13 UTC, AdvancerMan commented
> не знаю критично это или нет, но заметил что если 2 раза отказаться от какого-то запроса, то при следующем нажатии кнопки окно не появится.

Кстати, если уж мы по кнопке запрашиваем разрешения, то не запрашивать их -- неочевидное поведение. Я видел, что некоторые приложения (например, телега) отправляют сразу в меню настроек приложения и просят ручками включить разрешение. Такое трудно будет сделать? Если на это потратишь больше 1-2 часа, то давай просто текстовую пометку после "Not enough permissions" сделаем, что разрешение может не запроситься.

2023-07-31 07:18 UTC, AdvancerMan commented on application/app/src/main/res/layout/network_info_tab.xml
> +        android:backgroundTint="#0f62fe"
Если кто-то делает так -- это не значит, что так делать хорошо. Давай вынесем в константу

2023-08-01 12:09 UTC, AndyForWork commented
теперь цвет кнопкам подставляется с помощью @color/id
изменил сообщение о разрешениях, закинул его в файл со строками и теперь беру его от туда
изменил обработку нажатия кнопки. Теперь если отказаться от запрашиваемых разрешений, при следующем нажатии  кнопки будет перекидывать в настройки проги ( к сожалению сразу в раздел разрешений перекидывать не получается)

2023-08-01 12:09 UTC, AndyForWork commented
готов мерджить

2023-08-01 18:49 UTC, AdvancerMan approved these changes, later dismissed

2023-08-01 18:53 UTC, AdvancerMan approved these changes

2023-08-01 18:53 UTC, merged