suggest for main_address
5gst/5gst pull request #27
Opened 2023-07-27 15:23 UTC by Klanick

2023-07-27 16:42 UTC, AdvancerMan requested changes
Давай еще поаккуратнее код напишем, а так хорошо получилось!

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +    public HashMap<String, Date> getSuggestFromPrefs(){
В джаве конкретные реализации в типах не пишут. Обычно, пишут `Map<String, Date>`

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +        Gson gson = new Gson();
давай это сделаем как private static final  поле

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +
а почему это делается в speed activity?
кажется, этому место в start activity, например, [здесь](https://github.com/5Gst/5Gst/pull/27/files#diff-57b6067b8bd8726324fba97884f5ee62c4758181be04997ae73c979de1ad2dd3R201-R203)

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +        while (suggestMap.size() > 10) {
10 явно надо вынести в константу

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +        }
давай запишем это стримами
```kotlin
suggestMap.sortByDescending { it.date }.take(10)
```
так бы выглядело на котлине, давай то же самое напишем на джаве

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +                .limit(3)
3 в константы

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +    }
копипаста, починится при переносе логики в start activity

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +        HashMap<String, Date> suggestMap = getSuggestFromPrefs();
Map<String, Date>

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +                .filter(entry -> !entry.getKey().equals(searchValue))
это ты интересно придумал, зачем?)

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +                .sorted(Comparator.comparing(entry -> ((Map.Entry<String, Date>)entry)
не надо делать каст, давай нормально типизируем компаратор. Кажется, это делается так
```java
Comparator.<Map.Entry<String, Date>>comparing(...)
```

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +                        .thenComparing(Comparator.comparing(entry -> ((Map.Entry<String, Date>)entry)
аналогично с компаратором

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +            }
стоило бы тут как-то через xml создать шаблон саджеста, но будь как будет

(фиксить не надо)

2023-07-27 16:42 UTC, AdvancerMan commented on application/app/src/main/res/layout/activity_start.xml
> +                                -->
почему закомменчено?

2023-07-30 21:25 UTC, Klanick commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +
Ну вообще план был в том, чтобы явно гарантировать, что та строка которая добавится в саджест и та, по которой ведётся поиска это точна одна и та же. Но кажется это явно лишнее к тому, же и не очень много смысла делает

2023-07-31 07:26 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +    public Map<String, Date> getSuggestFromPrefs(){
а сделай везде ctrl + alt + L

2023-07-31 07:26 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/StartActivity.java
> +                        .sorted(Map.Entry.comparingByValue())
а ты тут не возьмешь 10 самых старых саджестов? нужно 10 самых новых

2023-07-31 07:26 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +
а в каком случае они могут различаться?

2023-07-31 07:28 UTC, AdvancerMan requested changes
еще чуть чуть порефакторить и можно мержить)

2023-07-31 17:24 UTC, AdvancerMan approved these changes

2023-07-31 17:30 UTC, Klanick commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +
Ну собственно ни в каком разумном.
А даже если они могут отличаться, то мы всё равно саджест пишем в первую очередь для того, что мы вводим в поле. Если даже там будут какие-то промежуточные изменения, то как-будто для саджеста важнее то, что было до

2023-07-31 17:46 UTC, merged