#19. Added customlogger.py as middleware logger for service and balancer
5gst/5gst pull request #28
Opened 2023-07-27 15:23 UTC by About-to-break

2023-07-27 16:25 UTC, AdvancerMan requested changes
Круто! Давай еще немного допишем кода, чтоб аккуратнее было, а так все хорошо

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/balancer/settings.py
> +    'custom_middleware.customlogger.LoggerMiddleware'
предлагаю ренейминг
custom_middleware -> middleware
customlogger -> logger
LoggerMiddleware -> FiveGstLoggerMiddleware

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +from django.utils.deprecation import MiddlewareMixin
а почему взято из `deprecation`? обычно так помечают что-то, что уже устарело

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +from django.utils.deprecation import MiddlewareMixin
Давай сделаем как [здесь](https://docs.djangoproject.com/en/4.2/topics/http/middleware/#writing-your-own-middleware)

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +    # noinspection PyMethodMayBeStatic
напиши коммент, почему тут саппресс

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +        if self.fuse:
а зачем self.fuse? давай, просто `if settings.DEBUG: ...`

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +                          'MORE_DATA': 'some sensitive data here', }
MORE_DATA убери, кому надо -- сам разберется

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +        logger.info(nonsensitive_data)
Давай допишем тут что-то типа "пришел реквест по методу {meta.get(...)} и пути {meta.get(...)} нонсенситив дата: {nonsensitive_data}"

2023-07-27 16:25 UTC, AdvancerMan commented on balancer/custom_middleware/customlogger.py
> +        logger.debug(sensitive_data)
и тут дописать лог месседж, как в нонсенситив логе

2023-07-27 16:25 UTC, AdvancerMan commented on service/custom_middleware/customlogger.py
> +        self.log(request)
Аналогично, комменты продублировать тут

2023-07-27 19:35 UTC, About-to-break commented on service/custom_middleware/customlogger.py
> +        self.log(request)
Понял, принял первым делом займусь этими правками

2023-07-28 15:11 UTC, AdvancerMan requested changes

2023-07-28 15:11 UTC, AdvancerMan commented on service/middleware/logger.py
> +                             }
Давай еще добавим адрес клиента
see https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django

2023-07-31 10:14 UTC, About-to-break commented
Почему-то не могу комментить в поле ниже...

Поясняю:
1. Добавленный метод раскрывает адресс, от  которого прилетела HTTP, он проверяет есть ли  в ней 'HTTP_X_FORWARDED_FOR', что означает наличие у нас какого-либо обратного прокси, если не учитывать вышесказанное, то адресс будет отображаться неверно (127.0.0.1).
2. В логах назвал ключ 'SENDER_ADDR', т.к. , к примеру,  мы имеем логи от сервисов в балансере, и называть их 'CLIENT_ADDR', не очень логично (мне кажется).

2023-07-31 17:12 UTC, AdvancerMan approved these changes

2023-07-31 19:16 UTC, merged