Сделал конструктор стейджей
5gst/5gst pull request #31
Opened 2023-07-29 11:40 UTC by AndyForWork

теперь можно стейджи удалять, сохранять и добавлять. Они автоматически применяются. При первом запуске создаются 2 базовых стейджа.

По поводу код ревью: в ListViewAdapter я не смог избавиться от ArrayList(заменить на List) - не хватает нужных методов, а с Array не будет работать из-за реализации адаптеров. В StageConfigurationParser столько методов для определения класса, т.к. без них прога не может сама отпределить что ей нужно вернуть, возвращает неправильный результат и ложится.

2023-07-29 13:12 UTC, AndyForWork commented
#3

2023-07-29 20:06 UTC, AdvancerMan requested changes
над чистотой кода бы еще поработать
видно, что опыта немного, но результат хороший, билд работает!

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/domain/StageConfiguration.kt
> +    var deviceArgs: String,
[Почему лучше использовать неизменяемые типы](https://web.mit.edu/6.005/www/fa15/classes/09-immutability/) (ссылку взял в гугле, подробно не валидировал, но на первый взгляд написано добротно).

Давай перепишем на val и будем использовать `newStageConfiguration = oldStageConfiguration.copy(name = newName, ...)` при изменении объекта

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +        adapter.add(StageConfiguration("New Stage","",""));
моя личная рекомендация: если по списку аргументов непонятно, что они значат, то надо добавлять имена

данный код предлагается переписать как
```kotlin
adapter.add(
  StageConfiguration(
    name = "New Stage",
    serverArgs = "",
    deviceArgs = "",
  )
)
```

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +    private lateinit var addBtn: Button
addButton

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +    private var arr: ArrayList<StageConfiguration>  =  ArrayList()
что такое arr? давай придумаем нормальный нейминг

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +    private var arr: ArrayList<StageConfiguration>  =  ArrayList()
это поле вообще используется?

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +        addBtn.setOnClickListener{addStage()}
давай везде сделаем ctrl + alt + L

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +        adapter = ListViewAdapter(requireActivity(), StageConfigurationParser().getStageFromPrefs(activity));
StageConfigurationParser() можно вынести в поле / константу

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/util/ListViewAdapter.kt
> +class ListViewAdapter(private val context: Activity, private val data: ArrayList<StageConfiguration>): ArrayAdapter<StageConfiguration>(context, R.layout.stage_sample, data) {
слишком абстрактный нейминг
скорее StageConfigurationListViewAdapter

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        Gson gson = new Gson();
gson можно вынести в поле / константу

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        saveToPrefs(context,R.string.pipeline_shared_storage_name,"firstTime",true);
скорее всего можно было вместо firstTime проверять, есть ли преф data
но окей, давай так оставим

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        saveToPrefs(context,R.string.pipeline_shared_storage_name,"data",map);
давай имена выносить в константы (тут "data")

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        return new TypeToken<ArrayList<StageConfiguration>>(){}.getType();
Утверждается, что единственное нетривиальное место, в котором следует использовать ArrayList вместо List это тут (возможно, с листом тоже сработает, но не уверен), потому что при десериализации создается конкретная реализация листа

Почему тебе нужен ArrayList в других местах -- не понял. Поясни, плиз

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        Integer in = 5;
?

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public <T> T getFromPrefs(Context context,Integer id,  String field, Class classType){
Class надо параметризовать

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public <T> T getFromPrefs(Context context,Integer id,  String field, Class classType){
давай метод сделаем приватным

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public <T> T getFromPrefs(Context context,Integer id,  String field, Class classType){
а почему Integer а не int?

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    }
для общего развития, на котлине это можно написать так
```kotlin
inline fun <reified T> getFromPrefs(context: Context, id: Int, field: String): T {
    Gson gson = new Gson();
    String json =
                context.getSharedPreferences(context.getString(id), MODE_PRIVATE).getString(
                        field,
                        null
                );
    return gson.fromJson(json, new TypeToken<T>(){}.getType())
}
```

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        ArrayList<StageConfiguration> map = getFromPrefs(context,R.string.pipeline_shared_storage_name,"data", ArrayList.class);
в параметре ArrayList нужен, в типе переменной -- нет

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +        ArrayList<StageConfiguration> map = getFromPrefs(context,R.string.pipeline_shared_storage_name,"data", ArrayList.class);
переименуй

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +            Boolean isFirstTime = getFromPrefs(context,R.string.pipeline_shared_storage_name,"firstTime",Boolean.class);
мб, все таки, откажемся от firstTime?

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/util/ListViewAdapter.kt
> +        val imgBtn = listViewNode.findViewById<ImageButton>(R.id.deleteButton);
imageButton, и даже наверное deleteButton

2023-07-29 20:06 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/util/ListViewAdapter.kt
> +        val stageName = listViewNode.findViewById(R.id.stage_name) as EditText;
Давай ко всем названиям добавим View, e.g. stageNameView -- так более очевидно, что в переменной

2023-07-30 17:06 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    }
если подобным образом сделать на джаве, то он не может правильно определить класс и приводить к LinkedTreeMap, а не к StageConfiguration. поэтому и пришлось сделать костыль чтобы не повторять код.

2023-07-30 17:14 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public <T> T getFromPrefs(Context context,Integer id,  String field, Class classType){
не совсем понял что именно нужно сделать. сделать classType типа T ? Если да, то тогда очень криво нужно будет передавать аргументы (Arraylist.class -> new Arraylist() и Boolean.class -> new Boolean(false)         (тут передал false, т.к. у Boolean нет конструктора без параметров) )

2023-07-30 18:16 UTC, AndyForWork commented
комменты учел, костыль в виде поля firstTime обошел

2023-07-30 18:41 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public <T> T getFromPrefs(Context context,Integer id,  String field, Class classType){
имеется в виду Class<T> (добавить `<T>`)

у тебя варнинги в андроид студии отключены? включи, пожалуйста, они бы это подсветили

2023-07-30 18:42 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    }
это да, джава не умеет в reified типы

тут просто пример, как на котлине можно классно писать

2023-07-30 19:00 UTC, AdvancerMan requested changes
Ишью, на которые рекомендую посмотреть, оставил. Остальные резолвнул. Типы с ArrayList все же реквестую починить там, где чинится (для понимания, где чинится, рекомендую почитать про дженерики в джаве, в том числе про type erasure)

на будущее: пожалуйста, к каждому комментарию пиши что сделал. Иногда было непонятно, код починил или проблемный кусок кода просто удалился

2023-07-30 19:00 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +                deviceArgs = ""
давай писать код с [trailing comma](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas)

2023-07-30 19:00 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SetupPipelineTab.kt
> +    private var stageConfigurationParser = StageConfigurationParser()
почему var?

2023-07-30 19:00 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/parser/StageConfigurationParser.java
> +    public ArrayList<StageConfiguration> getStageFromPrefs(Context context) {
почему тут ArrayList\<StageConfiguration\>? можно же List\<StageConfiguration\>

2023-08-01 10:56 UTC, AndyForWork commented
Class надо параметризовать - этого метода больше нет
trailing comma - сделал
var на val зменил 

по поводу замена Arraylist на List:

в StageConfigurationListViewAdapter заменил ArraLIst на MutableList ( не мог заменить просто на Array из-за реализации в котлине, не мог на List, т.к. не нашел методов удаления и замены (мб слепой....))
в StageConfigurationParser заменил возвращаемое значение в getStageFromPrefs с ArrayList на List, оставил ArrayList в Type и при возвращении если запускаем прогу в первый раз.

2023-08-01 10:56 UTC, AndyForWork commented
готов мерджить

2023-08-01 18:48 UTC, AdvancerMan approved these changes

2023-08-01 18:49 UTC, merged