#8 Improve error reporting and backend logging
5gst/5gst pull request #35
Opened 2023-08-02 11:51 UTC by IceMeladrom

2023-08-03 09:15 UTC, IceMeladrom commented
Готов мерджить

2023-08-03 19:05 UTC, AdvancerMan requested changes
еще надо поработать

2023-08-03 19:05 UTC, AdvancerMan commented on service/.gitignore
> +iperf_stats_logs/*.json
Это что?

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            raise BadRequest
почему ты кидаешь класс, а не объект?

имею в виду: почему не так:
`raise BadRequest("Not in session")`

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
пятисотку на 82-й строке тоже бы эксепшеном кидать

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            raise BadRequest
конструктор

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +    response = exception_handler(exc, context)
зачем тебе дефолтный exception_handler? мы же свой пишем

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +    response = exception_handler(exc, context)
давай создавать свой Response

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +    }
почему статус код в теле ответа, а не в в хттп коде?

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +        'default_detail': exc.default_detail,
что такое default_detail? давай считать, что тебе тут необязательно приходит APIException

если приходит он, то выводим сообщение из эксепшена
если не он, то отдаем 500 и выводим сообщение "Сервер еррор"

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +        'status_text': response.status_text,
а что такое status_text и чем он от default_detail отличается?

2023-08-03 19:05 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +    logger.exception(traceback.format_exc())
traceback.format_exc() ловит трейсбек последнего эксепшена, а он может быть не тем, что нужен

кажется, у логгера есть exc_info и можно логгировать так
```
logger.error(f"Error {status_code} happened: {error_message}", exc_info=exc)
```
предлагаю так же коды 4xx писать в logger.debug, а 5xx в logger.error

2023-08-03 19:05 UTC, AdvancerMan commented on service/service/settings.py
> +    'EXCEPTION_HANDLER': 'apps.logic.utils.custom_exception_handler.custom_exception_handler',
давай сделаем нейминг
'apps.logic.utils.exception_handler.handle_exception'

2023-08-03 19:05 UTC, AdvancerMan commented on service/service/settings.py
давай для балансера аналогичный хендлер добавим

2023-08-10 12:49 UTC, IceMeladrom commented on service/service/settings.py
> +    'EXCEPTION_HANDLER': 'apps.logic.utils.custom_exception_handler.custom_exception_handler',
сделал

2023-08-10 12:49 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exception_handler.py
> +    logger.exception(traceback.format_exc())
сделал

2023-08-10 12:49 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exception_handler.py
> +        'status_text': response.status_text,
убрал

2023-08-10 12:49 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exception_handler.py
> +        'default_detail': exc.default_detail,
сделал

2023-08-10 12:50 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exception_handler.py
> +    response = exception_handler(exc, context)
переделал

2023-08-10 12:50 UTC, IceMeladrom commented on service/apps/logic/session_web_service.py
> +            raise BadRequest
сделал

2023-08-10 12:51 UTC, IceMeladrom commented on service/apps/logic/session_web_service.py
сделал

2023-08-10 12:51 UTC, IceMeladrom commented on service/apps/logic/session_web_service.py
> +            raise BadRequest
сделал

2023-08-10 12:51 UTC, IceMeladrom commented on service/.gitignore
> +iperf_stats_logs/*.json
Убрал. Это случайно попало из первой версии PR #14

2023-08-10 17:12 UTC, AdvancerMan requested changes
давай то же самое сделаем на балансере
пока без перестановки импортов -- потом починим

2023-08-10 17:12 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exceptions.py
слово custom не несет вообще никакой семантики
давай переименуем файл в exceptions.py

2023-08-10 17:15 UTC, AdvancerMan commented on service/apps/logic/utils/custom_exception_handler.py
> +    response = exception_handler(exc, context)
если exception_handler не может похендлить эксепшн, то он возвращает None
давай в этом случае брать ситуацию в свои руки и возвращать Response("Server error", 500)

2023-08-10 17:28 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exceptions.py
убрал

2023-08-10 17:29 UTC, IceMeladrom commented
> давай то же самое сделаем на балансере пока без перестановки импортов -- потом починим

Добавил

2023-08-10 17:29 UTC, IceMeladrom commented on service/apps/logic/utils/custom_exception_handler.py
> +    response = exception_handler(exc, context)
исправил

2023-08-10 20:23 UTC, AdvancerMan requested changes

2023-08-10 20:23 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            # raise ValueError("I did it here.")
?

2023-08-10 20:26 UTC, AdvancerMan approved these changes

2023-08-10 20:31 UTC, merged