#15. Новая ручка для результатов
5gst/5gst pull request #37
Opened 2023-08-03 07:00 UTC by About-to-break

На данный момент:
Ручка всегда активна и вернет 200 если ее дернуть.
Ручка обернута в сваггер с сериализатором.
Параметры запуска перенесены в settings, но для теста приложения пока не используются

2023-08-03 07:09 UTC, About-to-break commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
Слэш на конце важен, без него выдаст 404

2023-08-03 07:11 UTC, About-to-break commented on service/apps/views.py
> +        print("StartSessionView")
Забыл убрать принты, сделаю после комментов

2023-08-04 18:36 UTC, AdvancerMan requested changes
что увидел откомментил, но как будто комментил каждый шаг
поправь, пожалуйста
велик шанс, что следующей итерацией тоже буду комментить

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +            return HttpResponseBadRequest()
ошибки давай рейзить, а не ретурнить

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +        return HttpResponse(response)
это можно записать через `Response(data=serialized_model.data, status=status.HTTP_200_OK)`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +        return HttpResponse(response)
это бы перенести в session_web_service

2023-08-04 18:36 UTC, AdvancerMan commented on service/service/settings.py
> +IPERF_UDP_DOWNLOAD_PARAMETERS = os.getenv('IPERF_UDP_DOWNLOAD_PARAMETERS', "-f b -i 0.1 -P 10 -b 120m --sum-only")
утверждается, что эта настройка тебе не нужна
если нужна, то утверждается, что ее не надо класть в енв (а то очень просто могут разъехаться параметры реальные и те, о которых мы думаем)

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +    @swagger_auto_schema(
так есть же SessionWebService.get_iperf_speed_results_swagger_auto_schema

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +        request_body=serializers.IperfSpeedResultsSerializer,
это не реквест, а респонс
см. SessionWebService.get_iperf_speed_results_swagger_auto_schema

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +        operation_id='send_results',
по сути этой фразой будет называться метод на клиенте
сенд -- как будто клиент шлет тебе
тут скорее `get_measurement_results`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +        security=[],
а это зачем?

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
давай слеш уберем

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/views.py
> +class IperfSpeedResultsAPIView(APIView):
остальные классы называются без View, а не APIView
давай делать однообразно и переименуем в IperfSpeedResultsView

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            # Seems sensitive to app. Changes kills session pipeline.
Очень странно
не помню, чтобы на приложении парсился error message
пояснишь, что именно и как именно не работает?

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +    def __stdout_processor_thread(self, stream: IO, file: TextIOWrapper):
давай называть метод не существительным, а глаголом
типа `__create_stdout_processor_thread`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +    def __stdout_processor_thread(self, stream: IO, file: TextIOWrapper):
и + мы же не только stdout парсим, но и stderr
тогда `__create_text_io_stream_processor_thread`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            if self.iperf_parameters.count('-u'):
мы же добавляем аргументы к udp upload
а это `-u` без `-R`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            # Check if we're having UDP download session
чтобы такие комменты не писать, предлагаю выделить логику в метод
check_is_udp_upload_command(str)

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +                "./iperf.elf " + '-p ' + str(port_iperf) + ' ' + self.iperf_parameters + ' ' + extra_iperf_parameters)
твой код ломается, если в него передать что-то типа `--ura` -- надо чекать не подстроку, а именно аргумент

у тебя же потом шлексом сплиттится команда, давай в масстве проверять содержание `-u`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +        def process(stream: IO, file: TextIOWrapper):
process_stream тогда уж

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_parser_container.py
> +    def __add_parsed_line(self, line: str):
почему __add_parsed_line, если ты line парсишь внутри метода?

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_parser_container.py
> +        self.probes = results
давай консистентный нейминг
results -> probes

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_parser_container.py
> +        self.__add_parsed_line(line)
?

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +        global iperf_active_parsed_speed_container
очень вредный способ использовать какой-то контейнер

давай его будем использовать не как глобальную переменную, которую меняем, а как контейнер, которому можем сказать `clear()`

2023-08-04 18:36 UTC, AdvancerMan commented on service/apps/logic/iperf_parser_container.py
> +        return IperfDownloadSpeedResultsContainer(self.probes[index:])
если ты вводишь сущность с названием probe (за отличительное название лайк) -- давай его использовать везде и консистентно

2023-08-07 20:00 UTC, About-to-break commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
Все нормально, уберу

2023-08-07 20:00 UTC, About-to-break commented on service/apps/logic/iperf_parser_container.py
> +                            "\\d+)(\\.\\d+)?\\s+bits/sec.*$"
Это из котлина без изменений

2023-08-07 20:00 UTC, About-to-break commented on service/apps/logic/iperf_parser_container.py
> +        return IperfDownloadSpeedResultsContainer(self.probes[index:])
Чтобы сохранить сериализатор

2023-08-07 20:00 UTC, About-to-break commented on service/apps/logic/iperf_wrapper.py
> -    def __init__(self, parameters: str = settings.IPERF_LAUNCH_PARAMETERS, verbose: bool = False) -> None:
Считаю было лишнее + имя не совсем отржает суть

2023-08-07 20:00 UTC, About-to-break commented on service/apps/logic/iperf_wrapper.py
> +        iperf_active_parsed_speed_container = None
Чтобы после завершения сессий нам снова отвечало 400 кодом по ручке

2023-08-07 20:00 UTC, About-to-break commented on service/apps/logic/session_web_service.py
> +            # Seems sensitive to app. Changes kills session pipeline.
Изначально тоже поменял, замер в приложении умер, видимо сенситивно для application

2023-08-07 20:00 UTC, About-to-break commented on service/apps/views.py
> +        start_index = request.GET.get('fromFrame')
На данный момент ручка вида: http://127.0.0.1:5004/api/v1/measurement/results/?fromFrame="..."

2023-08-07 20:00 UTC, About-to-break commented on service/service/settings.py
> +IPERF_UDP_DOWNLOAD_PARAMETERS = os.getenv('IPERF_UDP_DOWNLOAD_PARAMETERS', "-f b -i 0.1 -P 10 -b 120m --sum-only")
Мне кажется новый вариант понятнее, ну и функционал уже получил

2023-08-07 20:00 UTC, About-to-break commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
В официалке Django слэши вообще всегда есть, [пример](https://docs.djangoproject.com/en/4.2/topics/http/urls/).
А в нашем случае без этого работать не будет, либо могу сделать через регулярное выражение, вот [тут](https://stackoverflow.com/questions/150505/capturing-url-parameters-in-request-get) про все.

2023-08-07 20:00 UTC, About-to-break commented on service/apps/views.py
> +            return HttpResponseBadRequest()
HttpResponseBadRequest это не ошибка, подкласс HttpResponce, а конкретно эта строчка отправит 400 код на приложение, [подробнее](https://docs.djangoproject.com/en/4.2/ref/request-response/#httpresponse-subclasses).
Если хочешь сделать это ошибкой и рейзить ее, то предлагаю [что-то такое](https://stackoverflow.com/questions/25422176/django-raise-badrequest-as-exception).

2023-08-07 20:31 UTC, AdvancerMan commented on service/apps/views.py
> +            return HttpResponseBadRequest()
Ошибки предлагается рейзить, чтобы в логах писался трейсбек (после таски Роберта).
Предлагается рейзить эту ошибку: https://www.django-rest-framework.org/api-guide/exceptions/#validationerror

2023-08-07 20:34 UTC, AdvancerMan commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
В личке обсуждали. Тут напишу кратко, что я ожидаю:
* хочу единообразие, поэтому либо слеши везде, либо нигде
* хочу обратную совместимость, по возможности. Но наше приложение еще нигде публично не выложено, поэтому обратную совместимость можем ломать как хотим

в итоге: либо добавляй слеши сразу везде, либо не добавляй совсем

2023-08-07 20:36 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            # Seems sensitive to app. Changes kills session pipeline.
нужно поменять и убрать коммент

2023-08-08 21:35 UTC, About-to-break commented on service/apps/logic/iperf_wrapper.py
> +        global iperf_active_parsed_speed_container
От глобальности избавился, но в коде проверяю поле, хранящее контейнер по типу: is not None

2023-08-08 21:38 UTC, About-to-break commented on service/apps/logic/session_web_service.py
> +            # Seems sensitive to app. Changes kills session pipeline.
Починил, видимо баг был в другом

2023-08-08 22:00 UTC, About-to-break commented
Так-с... Если про что-то забыл, то стукай.

2023-08-08 22:02 UTC, About-to-break commented
Кодген не сработал... Я менял  в сваггере results -> probes через рефактор, может здесь проблема...

2023-08-08 22:04 UTC, About-to-break commented
Да, проблема в этом месте, но вроде как не из-за меня, он увидел переименование, но не смог применить, дай знать, поменяю обратно

2023-08-08 22:12 UTC, About-to-break commented
![image](https://github.com/5Gst/5Gst/assets/81954052/133e033c-f5ca-4de9-9a73-9a2be3f4fe59)

2023-08-09 07:16 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            # Seems sensitive to app. Changes kills session pipeline.
ну тогда давай коммент уберем

2023-08-09 07:16 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +        operation_id='iperf_speed_probes',
давай переименуем в get_iperf_speed_probes, чтоб глагол добавить
а то это имя потом прорастает в сгенерированный метод

2023-08-09 07:16 UTC, AdvancerMan commented on service/apps/urls.py
> +        path('measurement/results/', views.IperfSpeedResultsAPIView.as_view()),
по слешам вопрос еще не решен

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/serializers.py
> +    probes = serializers.ListField(child=serializers.IntegerField())
давай child определим как отдельный сериализатор -- так будет потом проще добавлять в него новые поля

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            raise BadRequest()
хочу сообщение об ошибке

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
>              ),
поменяй, пожалуйста TYPE_STRING на число

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
>                  'from_frame',
давай переименуем в from_probe

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +        start_index = request.GET.get('from_frame')
давай уберем зависимость от request и будем принимать сразу start_index

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            cmd = self.check_for_udp_download_mode(cmd)
check скорее bool должен возвращать
давай переименуем в transform или handle

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            if self.iperf_parameters.count('-u'):
все еще актуально

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            cmd += shlex.split(" -f b -i 0.1 -P 10 -b 120m --sum-only")
без -P 10 -b 120m

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +        self.is_udp_downloading = False
по сути это is_udp_uploading

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            self.iperf_active_parsed_speed_container = None
почему мы храним контейнер до окончания работы iperf? а вдруг он завершится ошибочно? давай удалять контейнер по ручкам /iperf/stop и /session/stop, а не когда айперф останавливается

2023-08-09 07:28 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            self.iperf_active_parsed_speed_container = None
почему мы храним контейнер до окончания работы iperf? а вдруг он завершится ошибочно? давай удалять контейнер по ручкам /iperf/stop и /session/stop, а не когда айперф останавливается

2023-08-09 07:29 UTC, AdvancerMan requested changes
уже похоже на что-то рабочее, давай еще отполируем)

2023-08-09 07:32 UTC, AdvancerMan commented
> Кодген не сработал... Я менял в сваггере results -> probes через рефактор, может здесь проблема...

должно сработать(  попробуй обновиться до актуальной ветки девелоп, у тебя в форке неактуальный CI

2023-08-10 14:01 UTC, About-to-break commented on service/apps/serializers.py
> +    probes = serializers.ListField(child=serializers.IntegerField())
Странное решение, учитывая, что я вырезал все кроме списка чисел, но оке

2023-08-10 14:13 UTC, About-to-break commented on service/apps/logic/session_web_service.py
>              ),
будет TYPE_INTEGER,

2023-08-10 14:19 UTC, About-to-break commented on service/apps/logic/session_web_service.py
> +        start_index = request.GET.get('from_frame')
start_index = request.GET.get('from_frame') -- тогда это в контроллере.

2023-08-10 14:34 UTC, About-to-break commented on service/apps/logic/iperf_wrapper.py
> +            self.iperf_active_parsed_speed_container = None
Тогда сделаю методом, буду вызывать по ручкам и до окончания, на всякий случай.

2023-08-10 14:46 UTC, About-to-break commented on service/apps/logic/iperf_wrapper.py
> +            self.iperf_active_parsed_speed_container = None
Перенес это в метод stop(), он вызывается по всем нужным ручкам.

2023-08-10 19:10 UTC, AdvancerMan requested changes

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +        if '-u' in cmd:
`if '-u' in cmd and '-R' not in cmd:`

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +        if '-u' in cmd:
и в комменте # Check if we're having UDP upload session

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/serializers.py
> +    bits_per_second = serializers.IntegerField(allow_null=True)
зачем serializers.IntegerField(allow_null=True)?

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/serializers.py
> +class IperfDownloadMeasurementSerializer(serializers.Serializer):
IperfMeasurementSerializer

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +            raise BadRequest("Requested Iperf speed probes on closed / non-existing session")
если start_index is None -- то месседж должен быть другой

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +    def get_iperf_speed_probes(self, start_index: int):
если в тип может прийти None, то пишут Optional, например
`Optional[int]`

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +        model = iperf_wrapper.iperf.iperf_active_parsed_speed_container.get_from_probe(int(start_index))
к тебе уже инт же пришел

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/session_web_service.py
> +        iperf_wrapper.iperf.wipe_probes_container()
давай это делать только на stop session

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +            cmd = self.handle_udp_download_mode(cmd)
handle_udp_upload_mode

2023-08-10 19:10 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> +                self.iperf_active_parsed_speed_container = iperf_parser_container.IperfDownloadMeasurementContainer()
лучше это делать до запуска треда, чтобы не попасть в гонку

2023-08-10 20:13 UTC, AdvancerMan requested changes

2023-08-10 20:13 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
>                      self.iperf_active_parsed_speed_container.append_line(str(stdout_line))
кстати, мы же не хотим парсить контент stderr? в любом случае пока не критично, давай так замержим (stderr все равно по регулярке не пройдет)

2023-08-10 20:13 UTC, AdvancerMan commented on service/apps/logic/iperf_wrapper.py
> -            self.wipe_probes_container()
тут логичнее бы оставить
и вообще, логичнее прямо здесь делать
```
if self.is_udp_uploading:
                self.iperf_active_parsed_speed_container = iperf_parser_container.IperfDownloadMeasurementContainer()
```
а не 2 раза для stdout и stderr

2023-08-10 20:15 UTC, AdvancerMan requested changes

2023-08-10 20:15 UTC, AdvancerMan commented on service/apps/views.py
> +        return session_web_service.get_iperf_speed_probes(int(start_index))
а если тут None придет?
если default=None убрать в GET.get что будет?

2023-08-10 20:16 UTC, AdvancerMan commented on service/apps/views.py
> +        return session_web_service.get_iperf_speed_probes(int(start_index))
кстати, а может поставим default=0?

2023-08-10 21:00 UTC, AdvancerMan approved these changes

2023-08-10 21:05 UTC, merged

2023-08-10 21:05 UTC, About-to-break commented
УРААААААААААААААААААААААААА