Замер трафика при помощи ручки
5gst/5gst pull request #43
Opened 2023-08-07 18:30 UTC by AndyForWork

класс StartIperfTask в зависимости от фругментов iperf либо работает как раньше, либо получает данные при помощи ручки (данные не дублируются), подправил несколько моментов чтобы оно работало (в ping менял с ServerAddress на ApiCLientHolder, который содержит в себе ServerAddress)

Отказался от идеи сделать финальный запрос на ручку в отдельной таске, т.к. это приведет к бесполезным действиям (придется дергать ручку не при udp upload), а небольшая разница в скорости при udp upload не значительна относительно задержек между стейджами)

2023-08-07 18:41 UTC, AndyForWork commented
возможно нужно будет сделать поправку на fromFrame при сохранении пришедших данных

2023-08-07 19:21 UTC, AndyForWork commented
не понятно нужно ли в этой таске чинить вылет проги при udp upload, просьба уточнить. В остальном готов мерджить

2023-08-07 20:28 UTC, AdvancerMan requested changes
надо рефакторить

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                    .port(apiClientHost.iperfAddress.port)
зачем тут ренейминг?

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
>                  .doTask(PingAddressTask(DEFAULT_TIMEOUT.toLong(), onPingUpdate))
зачем?
withArgumentExtracted же специально вычленяет адрес iperf'а только для пинга
а ты стал передавать в пинговую таску всех апишных клиентов --> пришлось в тасках менять аргументы

предлагаю вернуть тут .withArgumentExtracted { it.iperfAddress }

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                        .withArgumentExtracted { it }
вернуть it.iperfAddress

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartIperfTask.kt
> +        val api = GetDataByURL(argument)
имхо, тут лучше скопипастить логику в другой класс, чем запихивать два случая в один класс
у одного общего кода есть преимущества, да
но обычно абстрактный код сложен для понимания и поддержки, поэтому, тут давай покопипастим

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
>                          .doTask(startIperfTask)
ну и тут соответственно сделать иф

если upload --> запускаем одну таску
усли download --> другую

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                )
а это будет только у upload

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/res/values/strings.xml
> +    <string name="upload_device_iperf_args"> -P 10 -b 120m</string>
почему тут появился пробел?

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetUdpResultsTask.kt
> +class GetUdpResultsTask(
давай
GetMeasurementResultsTask

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetUdpResultsTask.kt
> +        return argument.serviceApiClient.iperfSpeedResultsAsync("5", callback)
fromFrame по дефолту давай 0

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetUdpResultsTask.kt
> +        onFinish(speedStatistics)
давай все же коллбек вызывать в следующей таске doUnstoppable
так код будет лучше декомпозирован

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private boolean running = true;
AtomicBoolean

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    }
а тред интерраптнуть?

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +        }
мы вот так просто втихую забудем про ексепшен?
не, не, не, давай хотя бы в onLog его писать

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +            fromFrame++;
fromFrame += results.size же

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private Integer fromFrame = 5;
начальное значение = 0

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private List<Integer> results = new ArrayList<>();
почти на все из этого можно добавить final

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    }
давай конструктор ставить в начале класса

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    }
а зачем нам его изменять извне?

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private Integer fromFrame = 5;
AtomicInteger

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private List<Integer> results = new ArrayList<>();
SynchronizedList

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartIperfTask.kt
> +        private val api: GetDataByURL,
очень странный нейминг

2023-08-07 20:28 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartIperfTask.kt
> +                        lastUdpResultIt += 1
зачем? мы же договорились сразу все результаты скармливать

2023-08-09 13:55 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                    .port(apiClientHost.iperfAddress.port)
исправил

2023-08-09 13:55 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
>                  .doTask(PingAddressTask(DEFAULT_TIMEOUT.toLong(), onPingUpdate))
исправил

2023-08-09 13:56 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                        .withArgumentExtracted { it }
исправил только в том месте, где используем старый класс. В новый класс нужно передавать ApiClientHodler (он используется для работы с апи), так что оставил так

2023-08-09 13:58 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartIperfTask.kt
> +        val api = GetDataByURL(argument)
создал новый класс (я конечно понимаю, что так мы разделям логику, но думаю что вместо нового класса можно было попробовать сделать новый метод)

2023-08-09 14:01 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
>                          .doTask(startIperfTask)
сделал иф чуть выше. Так пришлось больше копировать, но как по-другому сделать я не придумал

2023-08-09 14:12 UTC, AndyForWork commented
сделал все, кроме вызова коллбэка в след таске doUnstoppable. 
1) не совсем понимаю, зачем нужно работы с данными разбивать на 2 отдельных таска (зачем это логически разрывать?)
2) не уверен что это можно сделать так, чтобы не сломать структуру (если сделать таск на подобии StartIperfTask, то там код будет выполняться не 1 раз, а если сделать таск на подобии StartServiceIperfTask, то sendRequest обязан кидать call.

Так же тепереь все результаты сразу сохраняю,но из-за этого даже та минимальная плавность которая была пропала (теперь мы показываем только одно значение раз в секунду, что не очень хорошо)

Все остальные изменения учел

2023-08-09 18:48 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                    .andThen(DelayTask(idleBetweenTasksMelees))
давай task consumer для upload и не download будем в отдельном методе собирать. Методы на ~100 строк -- плохая практика для понимания кода

2023-08-09 18:48 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                        .withArgumentExtracted { it }
ок, давай еще тут отрефачим
```
.withArgumentExtracted { it }.doTask(startUdpUploadIperfTask)
```
это эквивалентно следующему:
```
.andThen(startUdpUploadIperfTask)
```

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetMeasurementResultsTask.kt
> +    }
тут надо либо в аргумент пропихивать speedStatistics, либо результатом отдавать
иначе придется с многопоточкой сражаться

почему бы не пойти в iperfSpeedResultsAsync(0) и потом в новый LongSummaryStatistics не сложить полученные результаты?
его возвращаем как результат таски и уже сверху кладем в onFinish

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            }
зачем? мы же результаты с бэка получаем
давай удалим это

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +        const val LOG_TAG = "StartIperfTask"
давай тут поставим StartUdpUploadIperfTask::class.name

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +        private val measurementResults: GetDataByURL,
прям большие проблемы с неймингом в этом месте
это точно не measurementResults -- это какой-то пинговальщик результатов, а не сами результаты
это точно не GetDataByURL -- по такому абстрактному названию вообще непонятно, что оно связано с результатами замера

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            thread.interrupt()
не очень хорошо, что ты разносишь остановку таски в два разных места

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +            Log.e("GetDataByURL - Exception","ApiException " +e.toString());
прокинь сюда колбэк `onLog: (String, String, Exception?) -> Unit`, чтобы писать в логи, которые видит пользователь

2023-08-09 19:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartIperfTask.kt
> +        private val api: GetDataByURL,
нейминг стал еще страннее

2023-08-09 19:08 UTC, AdvancerMan requested changes
я не верю, что твой код работает)
давай напишем так, чтобы я поверил

2023-08-09 19:08 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +            results = Collections.synchronizedList(apiClientHolder.getServiceApiClient().iperfSpeedResults(fromFrame.toString()).getResults());
ты сделал только хуже
тебе тут нужен AtomicReference<List>, а не synchronized list

2023-08-09 19:08 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    private List<Integer> results = Collections.synchronizedList(new ArrayList<Integer>());
доставь final

2023-08-09 19:08 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +            results = Collections.synchronizedList(apiClientHolder.getServiceApiClient().iperfSpeedResults(fromFrame.toString()).getResults());
впрочем, предлагаю сразу в этом методе и прокидывать данные в коллбэк, эквалайзер и тд.
тогда synchronized list будет достаточно

2023-08-09 19:08 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/GetDataByURL.java
> +    }
это тебе не нужно

2023-08-09 19:12 UTC, AdvancerMan commented
> сделал все, кроме вызова коллбэка в след таске doUnstoppable.
> 
>     1. не совсем понимаю, зачем нужно работы с данными разбивать на 2 отдельных таска (зачем это логически разрывать?)
> 
>     2. не уверен что это можно сделать так, чтобы не сломать структуру (если сделать таск на подобии StartIperfTask, то там код будет выполняться не 1 раз, а если сделать таск на подобии StartServiceIperfTask, то sendRequest обязан кидать call.
> 
> 
> Так же тепереь все результаты сразу сохраняю,но из-за этого даже та минимальная плавность которая была пропала (теперь мы показываем только одно значение раз в секунду, что не очень хорошо)
> 
> Все остальные изменения учел

1. мы это разрываем для упрощения кода. Красивые математические абстракции часто некрасиво выглядят в реальной жизни. Тут ты избавился от постоянных ифов на -u -R, когда разделил таски. Имхо, код стал проще для понимания
2. ты сделал все почти как я ожидал, подстраиваться под все абстракции не нужно -- опять же, некрасиво в реальной жизни

Плавность будем повышать уменьшением таймаута с 1 секунды до меньших интервалов

2023-08-10 16:57 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                    .andThen(DelayTask(idleBetweenTasksMelees))
разбил на 2 разных метода, где создаются mutableTask либо для StartUdpUploadIperfTask, либо для StartIperfTask. Конечно методы не оч, но помогают разгрузить код.

2023-08-10 17:19 UTC, AndyForWork commented
починил все что сломал до этого, разбил в DownloadUploadSpeedTestManager создание тасок на методы, поменял названия (стало только хуже), теперь работа с результатами апи идет через колбэк


И все еще старый вопрос - ломается прога при использовании UDP Upload прога. (пока свой код тестю подставляя в иф true) Как я понимаю там где-то при использовании iperf'a внутри трабл (то, что я еще не успел тронуть/испротить/переименовать). Чинить ?

2023-08-10 17:20 UTC, AndyForWork commented
можно мерджить

2023-08-10 17:37 UTC, AdvancerMan commented
> И все еще старый вопрос - ломается прога при использовании UDP Upload прога. (пока свой код тестю подставляя в иф true) Как я понимаю там где-то при использовании iperf'a внутри трабл (то, что я еще не успел тронуть/испротить/переименовать). Чинить ?

Да, чинить

2023-08-10 17:54 UTC, AdvancerMan requested changes

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                        )
давай вытащим в переменную

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +                        )
давай вытащим в переменную

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +import io.swagger.annotations.Api
зачем?

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                        val equalizedSpeed = try {
у тебя тут ворнинг
ворнинги надо чинить
> Variable 'equalizedSpeed' is never used

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            i+=1
зачем?

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            i+=1
давай складывать line в onLog

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +                process(Collections.synchronizedList(results))
зачем synchronizedList? у тебя тут многопоточности вообще нет

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +    private var results = Collections.synchronizedList(ArrayList<Int>())
если у тебя поле не final -- его нужно делать AtomicReference или Volatile

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +    private var results = Collections.synchronizedList(ArrayList<Int>())
тебе вообще эта переменная не нужна

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +                process(Collections.synchronizedList(results))
в process нужно складывать только хвост результатов, а не все результаты

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +    private val process: (List<Int>) -> Unit
странный нейминг

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +        const val LOG_TAG = "GetDataByURL"
IperfMeasurementPinger::class.name

2023-08-10 17:54 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                    if (speedEqualizer.accept(data[i].toLong())) {
зачем 2 раза accept 0.0

2023-08-10 18:34 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +                process(Collections.synchronizedList(results))
так мы же каждый раз сдвигаем fromframe так, чтобы получать только новые данные (и соответственно в results храним только хвост) (ты сам сказал так сделать)

2023-08-11 07:00 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +                process(Collections.synchronizedList(results))
да, теперь норм

2023-08-11 07:04 UTC, AdvancerMan requested changes

2023-08-11 07:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                    val equalizedSpeed = try {
ты тут забыл speedStatistics.accept()

2023-08-11 07:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            if (speedEqualizer.accept(el.toLong())) {
отступ съехал

2023-08-11 07:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +            onLog("line",line, null)
onLog("iPerf stdout", ...

2023-08-11 07:04 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +            if (args.contains("-u") && !args.contains("-R")) {
нужно проверять на самом деле регулярку `\b-u\b` и `\b-R\b`

2023-08-11 07:09 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                }
это надо делать под локом

2023-08-13 12:45 UTC, AdvancerMan requested changes

2023-08-13 12:45 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +                Thread.sleep(100)
вынеси 100 в константу

2023-08-13 12:45 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                thread.start()
почему у тебя thread.start в цикле?

2023-08-13 12:45 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                        thread.interrupt()
што

2023-08-13 12:45 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/IperfMeasurementPinger.kt
> +        while (true) {
while thread is not interrupted тогда

2023-08-15 13:58 UTC, AndyForWork commented
все исправил, можно мерджить

2023-08-15 19:09 UTC, AdvancerMan requested changes

2023-08-15 19:09 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/activities/SpeedActivity.java
> +                }))
зачем нам еще коллбек? мы же можем это делать в onStageStart

2023-08-15 19:09 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +            context.getString(R.string.delay_before_start_iperf).toLong(),
зачем это в андроидных стрингах? почему не константа в коде?

2023-08-15 19:09 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                    onLog(LOG_TAG, "Equalizer $e", e)
зачем $e добавлять в месседж? ты же и так ошибку передаешь в коллбек

2023-08-15 19:09 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                onConnectionWait(false)
мы же можем при первом onSpeedUpdate начинать показывать скорость, зачем этот коллбек?

2023-08-15 19:10 UTC, AdvancerMan requested changes

2023-08-15 19:10 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +        Thread.sleep(delayBeforeStartIperf)
синхронно спать не надо

2023-08-15 19:10 UTC, AdvancerMan requested changes

2023-08-15 19:10 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +            if (args.contains("-u") && !args.contains("-R")) {
все еще актуально

2023-08-17 09:49 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +            if (args.contains("-u") && !args.contains("-R")) {
а почему именно такая проверка???? у нас ведь -u не граничит с концом строки (-u -P 10 -b 120m). Да и -R никогда не граничит с границами. не понимаю, почему такие условия.... Нам ведь главное проверить что udp (-u) и не tcp (нет -R в команде) используются одновременно.

2023-08-17 09:53 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +        Thread.sleep(delayBeforeStartIperf)
я решил что нет смысла вообще в слипе. Сейчас скорость первого ответа около секунды. При этом последующие ответы тоже приходят за 0,8+-0,2 сек, так что эта 1 сек ничего не даст (она появляется из-за того, что первый ответ на самом деле приходит пустым, первые пустые ответы я пропускаю, а следующий ответ приходит через 1 сек)

2023-08-17 11:43 UTC, AndyForWork commented
Нашел ошибку, которая возникает при udp upload при использовании и нового класса, и старого: если в процессе остановить работу , то при следующем запуске в логе будет "Could not connect to balancer (status code = 500)", и ничего не запустится. Приэтом, если снова попробовать запустить, то будет все ок.  (Это не критично, просто нашел)

2023-08-17 12:37 UTC, AndyForWork commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                onConnectionWait(false)
есть несколько причин:
1) он используется только в udp upload и просто так добавлять его для обычного режима смысла мало (ну зачем нам всегда ставить false еще одним параметром?)
2) он необходим, т.к. если при udp upload мы остановим работу, то при следующем запуске надпись останется, а цифр не будет.Также не отработает task'a, которая финальный раз дергает ручку, а еще как-то отследить что работа закончена мы не можем.

2023-08-26 08:15 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/manager/DownloadUploadSpeedTestManager.kt
> +            if (args.contains("-u") && !args.contains("-R")) {
Потому что ты проверяешь подстроку, а не аргумент iperf'а. У iperf'а, например, есть аргумент `--udp-histogram`, что само по себе не означает `-u`, но под твое условие подходит

2023-08-26 08:19 UTC, AdvancerMan commented on application/app/src/main/java/ru/scoltech/openran/speedtest/task/impl/StartUdpUploadIperfTask.kt
> +                onConnectionWait(false)
> он используется только в udp upload и просто так добавлять его для обычного режима смысла мало (ну зачем нам всегда ставить false еще одним параметром?)

причем тут обычный режим, я не понял

> если при udp upload мы остановим работу, то при следующем запуске надпись останется

можно добавить "восстановление UI" на коллбек onStop

> Также не отработает task'a, которая финальный раз дергает ручку, а еще как-то отследить что работа закончена мы не можем

это архитектурная проблема. Сейчас у нас остановка замеров, значит остановку всего без показа финальных результатов. Так что пока это норм

2023-08-26 09:23 UTC, AdvancerMan approved these changes

2023-08-26 09:44 UTC, merged